set(_CATKIN_CURRENT_PACKAGE "robot_specific_msgs")
set(robot_specific_msgs_VERSION "0.0.0")
set(robot_specific_msgs_MAINTAINER "Erhard Wieser <erhard.wieser@tum.de>")
set(robot_specific_msgs_PACKAGE_FORMAT "1")
set(robot_specific_msgs_BUILD_DEPENDS "message_generation" "std_msgs")
set(robot_specific_msgs_BUILD_EXPORT_DEPENDS "message_runtime" "std_msgs")
set(robot_specific_msgs_BUILDTOOL_DEPENDS "catkin")
set(robot_specific_msgs_BUILDTOOL_EXPORT_DEPENDS )
set(robot_specific_msgs_EXEC_DEPENDS "message_runtime" "std_msgs")
set(robot_specific_msgs_RUN_DEPENDS "message_runtime" "std_msgs")
set(robot_specific_msgs_TEST_DEPENDS )
set(robot_specific_msgs_DOC_DEPENDS )
set(robot_specific_msgs_DEPRECATED "")